/**
 * Content collection layer.
 *
 * Single source of truth = the markdown files under `public/content/`.
 * Each file carries YAML frontmatter (title, description, date, image, ...).
 * Everything that used to be hand-maintained lists (blog index, projects index,
 * aperture gallery tiles, RSS feed) is now generated by scanning these files.
 *
 * To add content you just drop a new `.md` file with frontmatter — nothing else
 * needs updating. Server-side only (uses fs); import from server components and
 * route handlers / build scripts.
 */
import { readFileSync, readdirSync, existsSync, statSync } from "fs";
import { join } from "path";
import matter from "gray-matter";
import exifr from "exifr";

export const SITE_URL = "https://lucashanson.dk";

const CONTENT_DIR = join(process.cwd(), "public", "content");

/* ------------------------------------------------------------------ */
/* Types                                                               */
/* ------------------------------------------------------------------ */

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  keywords?: string[];
  date: string; // ISO yyyy-mm-dd
  image?: string;
  /** Markdown body, frontmatter stripped. */
  body: string;
}

export interface Project {
  slug: string;
  title: string;
  tagline: string;
  description: string;
  keywords?: string[];
  image?: string;
  tags?: string[];
  date?: string;
  /** Markdown body, frontmatter stripped. */
  body: string;
}

export interface Gallery {
  id: string;
  title: string;
  description: string;
  cover?: string;
  imageCount: number;
  /** Markdown after the gallery's separator, for links and notes. */
  afterword?: string;
}

export interface FrontpageMeta {
  name: string;
  tagline: string;
  profileImage?: string;
  heroImage?: string;
  /** Markdown body, frontmatter stripped. */
  body: string;
}

/* ------------------------------------------------------------------ */
/* Low-level helpers                                                   */
/* ------------------------------------------------------------------ */

const IMAGE_EXTENSIONS = new Set(["jpg", "jpeg", "png", "webp", "gif", "avif"]);

function listMarkdownFiles(dir: string): string[] {
  try {
    return readdirSync(dir)
      .filter((f) => f.toLowerCase().endsWith(".md"))
      .sort();
  } catch {
    return [];
  }
}

/**
 * Read + parse a markdown file, returning null instead of throwing when the
 * file is missing, unreadable, or has malformed frontmatter. A single broken
 * file must not take down the whole site/build.
 */
function readParsedSafe(dir: string, name: string): { data: any; content: string } | null {
  try {
    const raw = readFileSync(join(dir, name), "utf8");
    return matter(raw);
  } catch (err) {
    console.warn(`[content] Skipping ${join(dir, name)}: ${(err as Error).message}`);
    return null;
  }
}

/**
 * Extract the first `![header](/path)` image reference from a markdown string.
 * Returns the path or undefined. Kept as a fallback for files that use the
 * legacy header-image convention instead of an `image`/`cover` frontmatter field.
 */
function extractHeaderImage(markdown: string): string | undefined {
  const match = markdown.match(/!\[[^\]]*\]\(([^)\s]+)/);
  return match ? match[1] : undefined;
}

function firstHeading(markdown: string): string | undefined {
  const line = markdown
    .split("\n")
    .find((l) => l.trim().startsWith("#"));
  if (!line) return undefined;
  return line.replace(/^#+\s*/, "").trim();
}

/**
 * Remove legacy header/profile image lines and a leading `---` divider from a
 * markdown body. These are now represented by frontmatter (`image` / `cover` /
 * `profileImage`) or the page hero, so keeping them inline would duplicate the
 * header image. All other inline images are preserved.
 */
export function cleanBody(markdown: string): string {
  return markdown
    .split("\n")
    .filter((l) => !/^!\s*\[header\]/i.test(l.trim()) && !/^!\s*\[profile picture\]/i.test(l.trim()))
    .join("\n")
    .replace(/^\s*---\s*\n/, "")
    // Detail pages render the frontmatter title as their sole h1.
    .replace(/^\s*# [^\n]+\n+/, "")
    .trimStart();
}

/**
 * First non-empty, non-heading, non-image paragraph line — used as a
 * description fallback when frontmatter omits one.
 */
function firstParagraph(markdown: string): string {
  const line = markdown
    .split("\n")
    .find(
      (l) =>
        l.trim() &&
        !l.startsWith("#") &&
        !l.startsWith("![") &&
        !l.startsWith("---") &&
        !l.startsWith("##")
    );
  return line ? line.trim() : "";
}

/**
 * Parse a `keywords` frontmatter value into a clean string array.
 * Accepts either a YAML array (`keywords: [a, b]`) or a comma-separated
 * string. Returns undefined when absent or empty so the meta tag is omitted.
 */
function parseKeywords(data: any): string[] | undefined {
  if (Array.isArray(data.keywords)) {
    const kws = (data.keywords as unknown[]).map((t) => String(t).trim()).filter(Boolean);
    return kws.length ? kws : undefined;
  }
  if (typeof data.keywords === "string" && data.keywords) {
    const kws = data.keywords.split(",").map((t) => t.trim()).filter(Boolean);
    return kws.length ? kws : undefined;
  }
  return undefined;
}

function isoDate(value: unknown, fallback = "1970-01-01"): string {
  if (typeof value === "string" && value.trim()) return value.trim();
  if (value instanceof Date && !isNaN(value.getTime())) {
    return value.toISOString().slice(0, 10);
  }
  return fallback;
}

/* ------------------------------------------------------------------ */
/* Blog                                                                */
/* ------------------------------------------------------------------ */

export function getBlogPosts(): BlogPost[] {
  const dir = join(CONTENT_DIR, "blog");
  if (!existsSync(dir)) return [];

  const posts = listMarkdownFiles(dir).map((file): BlogPost | null => {
    const slug = file.replace(/\.md$/i, "");
    const parsed = readParsedSafe(dir, file);
    if (!parsed) return null;
    const { data, content } = parsed;
    return {
      slug,
      title: (data.title as string) || firstHeading(content) || slug,
      description:
        (data.description as string) || firstParagraph(content).slice(0, 160),
      keywords: parseKeywords(data),
      date: isoDate(data.date),
      image: (data.image as string) || extractHeaderImage(content),
      body: cleanBody(content),
    } satisfies BlogPost;
  }).filter((p): p is BlogPost => p !== null);

  posts.sort((a, b) => b.date.localeCompare(a.date));
  return posts;
}

export function getBlogPost(slug: string): BlogPost | undefined {
  return getBlogPosts().find((p) => p.slug === slug);
}

/* ------------------------------------------------------------------ */
/* Projects                                                            */
/* ------------------------------------------------------------------ */

export function getProjects(): Project[] {
  const dir = join(CONTENT_DIR, "projects");
  if (!existsSync(dir)) return [];

  const projects = listMarkdownFiles(dir).map((file): Project | null => {
    const slug = file.replace(/\.md$/i, "");
    const parsed = readParsedSafe(dir, file);
    if (!parsed) return null;
    const { data, content } = parsed;
    const tags = Array.isArray(data.tags)
      ? (data.tags as unknown[]).map((t) => String(t))
      : typeof data.tags === "string" && data.tags
        ? data.tags.split(",").map((t) => t.trim()).filter(Boolean)
        : undefined;

    return {
      slug,
      title: (data.title as string) || firstHeading(content) || slug,
      tagline:
        (data.tagline as string) || firstHeading(content) || "",
      description:
        (data.description as string) || firstParagraph(content).slice(0, 160),
      keywords: parseKeywords(data),
      image: (data.image as string) || extractHeaderImage(content),
      tags,
      date: data.date ? isoDate(data.date) : undefined,
      body: cleanBody(content),
    } satisfies Project;
  }).filter((p): p is Project => p !== null);

  // Most recent first when dates exist; keep stable order otherwise.
  projects.sort((a, b) => (b.date || "").localeCompare(a.date || ""));
  return projects;
}

export function getProject(slug: string): Project | undefined {
  return getProjects().find((p) => p.slug === slug);
}

/* ------------------------------------------------------------------ */
/* Aperture galleries                                                  */
/* ------------------------------------------------------------------ */

/** Count image files in a gallery directory (mirrors useGalleryImages rules). */
function countImages(galleryId: string): number {
  const dir = join(process.cwd(), "public", "images", galleryId);
  try {
    return readdirSync(dir).filter((f) => {
      const ext = f.split(".").pop()?.toLowerCase() ?? "";
      return IMAGE_EXTENSIONS.has(ext);
    }).length;
  } catch {
    return 0;
  }
}

export function getGalleries(): Gallery[] {
  const imagesDir = join(process.cwd(), "public", "images");
  const metaDir = join(CONTENT_DIR, "aperture");

  // Discovery is the union of aperture markdown files and image directories, so
  // dropping EITHER one surfaces a gallery. Markdown-only galleries stay hidden
  // until photos are added (a zero-photo gallery is useless).
  let dirIds: string[] = [];
  try {
    dirIds = readdirSync(imagesDir, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name);
  } catch {
    // no images dir yet
  }

  let metaIds: string[] = [];
  try {
    metaIds = readdirSync(metaDir)
      .filter((f) => f.toLowerCase().endsWith(".md"))
      .map((f) => f.replace(/\.md$/i, ""));
  } catch {
    // no aperture meta dir yet
  }

  const ids = Array.from(new Set([...dirIds, ...metaIds])).sort();

  const galleries: Gallery[] = [];
  for (const id of ids) {
    const imageCount = countImages(id);
    if (imageCount === 0) continue;
    let title = id;
    let description = "";
    let cover: string | undefined;
    let afterword: string | undefined;

    const metaFile = join(metaDir, `${id}.md`);
    if (existsSync(metaFile)) {
      const parsed = readParsedSafe(metaDir, `${id}.md`);
      if (parsed) {
        const { data, content } = parsed;
        title = (data.title as string) || firstHeading(content) || id;
        description = (data.description as string) || firstParagraph(content);
        cover = (data.cover as string) || extractHeaderImage(content);
        afterword = content.split(/^\s*---\s*$/m).slice(1).join("\n---\n").trim() || undefined;
      }
    }

    // If no explicit cover, use the first image in the folder as the tile.
    if (!cover) {
      const first = firstImageInDir(join(process.cwd(), "public", "images", id));
      if (first) cover = `/images/${id}/${first}`;
    }

    galleries.push({
      id,
      title,
      description,
      cover,
      imageCount,
      afterword,
    } satisfies Gallery);
  }

  return galleries;
}

function firstImageInDir(dir: string): string | undefined {
  try {
    const files = readdirSync(dir)
      .filter((f) => {
        const ext = f.split(".").pop()?.toLowerCase() ?? "";
        return IMAGE_EXTENSIONS.has(ext);
      })
      .sort();
    return files[0];
  } catch {
    return undefined;
  }
}

export interface GalleryImage {
  src: string;
  alt: string;
  /** Camera make/model from EXIF, e.g. "FUJIFILM X-E4". */
  camera?: string;
  /** Shot date (yyyy-mm-dd) from EXIF, falling back to a date in the filename. */
  date?: string;
}

const SAFE_PATH_SEGMENT = /^[A-Za-z0-9._ -]+$/;

/** Clean an EXIF date value into yyyy-mm-dd. */
function exifDate(value: unknown): string | undefined {
  if (value instanceof Date && !isNaN(value.getTime())) {
    return value.toISOString().slice(0, 10);
  }
  if (typeof value === "string" && value) {
    const m = value.match(/(20\d{2})[:\-.](\d{2})[:\-.](\d{2})/);
    if (m) return `${m[1]}-${m[2]}-${m[3]}`;
  }
  return undefined;
}

/**
 * List all images in a gallery directory with EXIF-derived metadata
 * (camera + shot date) used by the Art Gallery captions.
 * Server-side (fs + exifr). A broken/EXIF-less file just gets no metadata.
 */
export async function getGalleryImages(galleryId: string): Promise<GalleryImage[]> {
  if (!SAFE_PATH_SEGMENT.test(galleryId) || galleryId.includes("..")) {
    return [];
  }
  const dir = join(process.cwd(), "public", "images", galleryId);
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true }).filter((e) => {
      if (!e.isFile()) return false;
      const ext = e.name.split(".").pop()?.toLowerCase() ?? "";
      return IMAGE_EXTENSIONS.has(ext);
    });
  } catch {
    return [];
  }

  const images = await Promise.all(
    entries.map(async (e) => {
      const src = `/images/${galleryId}/${e.name}`;
      const alt = e.name.replace(/\.[^.]+$/, "").replace(/[-_]/g, " ").trim();
      let camera: string | undefined;
      let date: string | undefined;
      try {
        const meta: any =
          (await exifr.parse(join(dir, e.name), {
            pick: ["Make", "Model", "DateTimeOriginal", "DateTime", "ModifyDate"],
          })) || {};
        if (meta?.Make || meta?.Model) {
          camera =
            [meta.Make, meta.Model]
              .filter(Boolean)
              .join(" ")
              .replace(/_/g, " ")
              .trim();
        }
        date =
          exifDate(meta?.DateTimeOriginal) ||
          exifDate(meta?.DateTime) ||
          exifDate(meta?.ModifyDate);
      } catch {
        // no readable EXIF — fine, we just have no metadata
      }
      if (!date) {
        const m = e.name.match(/(20\d{2})(\d{2})(\d{2})/);
        if (m) date = `${m[1]}-${m[2]}-${m[3]}`;
      }
      return { src, alt, camera, date };
    })
  );

  return images.sort((a, b) => a.src.localeCompare(b.src));
}

/* ------------------------------------------------------------------ */
/* Frontpage                                                           */
/* ------------------------------------------------------------------ */

export function getFrontpage(): FrontpageMeta {
  const file = join(CONTENT_DIR, "frontpage.md");
  if (!existsSync(file)) {
    return { name: "Lucas Hanson", tagline: "", body: "" };
  }
  const parsed = readParsedSafe(CONTENT_DIR, "frontpage.md");
  if (!parsed) return { name: "Lucas Hanson", tagline: "", body: "" };
  const { data, content } = parsed;
  return {
    name: (data.name as string) || "Lucas Hanson",
    tagline: (data.tagline as string) || "",
    profileImage: data.profileImage as string | undefined,
    heroImage: (data.heroImage as string) || extractHeaderImage(content),
    body: content,
  };
}

/* ------------------------------------------------------------------ */
/* Frontpage structured sections                                       */
/* ------------------------------------------------------------------ */

export interface FrontpageSection {
  /** Heading text without the leading `##` and emoji, e.g. "IT Work experience". */
  title: string;
  /** Leading emoji if present. */
  emoji: string;
  /** Raw markdown content under the heading. */
  content: string;
  /** Parsed `###` entries (role/org/dates) when the section is a list of them. */
  entries: ExperienceEntry[];
}

export interface ExperienceEntry {
  title: string;
  org?: string;
  orgUrl?: string;
  dates?: string;
  description: string;
}

/**
 * Split a frontpage body into an intro (everything before the first `##`)
 * plus one section per `##` heading. Sections that contain `###` entries are
 * parsed into structured ExperienceEntry objects for the timeline layout.
 */
export function parseFrontpage(body: string): {
  intro: string;
  sections: FrontpageSection[];
} {
  const lines = body.split("\n");
  const h2Indices = lines
    .map((l, i) => (l.trim().startsWith("## ") ? i : -1))
    .filter((i) => i >= 0);

  const intro =
    h2Indices.length > 0 ? lines.slice(0, h2Indices[0]).join("\n") : body;

  const sections: FrontpageSection[] = h2Indices.map((start, idx) => {
    const end =
      idx + 1 < h2Indices.length ? h2Indices[idx + 1] : lines.length;
    const headingLine = lines[start];
    const rawTitle = headingLine.replace(/^##\s*/, "").trim();
    const emoji = extractLeadingEmoji(rawTitle);
    const title = rawTitle.replace(emoji, "").trim();
    const content = lines.slice(start + 1, end).join("\n").trim();
    return {
      title,
      emoji,
      content,
      entries: content.includes("### ") ? parseEntries(content) : [],
    };
  });

  return { intro, sections };
}

function extractLeadingEmoji(text: string): string {
  // Include ZWJ (U+200D) so multi-codepoint emoji are stripped whole.
  const m = text.match(/^((?:\p{Extended_Pictographic}|\uFE0F|\u200D)+)\s*/u);
  return m ? m[0].replace(/\s+$/, "") : "";
}

/**
 * Parse `###` entries from a section body. Each entry looks like:
 *   ### Role
 *   **[Org](url)** - *(dates)*\\
 *   description...
 */
function parseEntries(content: string): ExperienceEntry[] {
  const parts = content.split(/(?=^###\s)/m);
  const entries: ExperienceEntry[] = [];

  for (const part of parts) {
    if (!part.trim().startsWith("### ")) continue;
    const lines = part.split("\n");
    const title = lines[0].replace(/^###\s*/, "").trim();
    const rest = lines.slice(1).join("\n");

    // Match the org + dates line: **[Org](url)** - *(dates)*
    const orgMatch = rest.match(
      /\*\*\[([^\]]+)\]\(([^)]+)\)\*\*\s*[-–]\s*\*?\(?([^)\n]*)\)?\*?/
    );
    let org: string | undefined;
    let orgUrl: string | undefined;
    let dates: string | undefined;
    let descriptionSource = rest;

    if (orgMatch) {
      org = orgMatch[1];
      orgUrl = orgMatch[2];
      dates = orgMatch[3].trim();
      // Remove the org line so it is not duplicated in the description.
      descriptionSource = rest.replace(orgMatch[0], "").trim();
    }

    const description = descriptionSource
      // Collapse markdown hard-break backslashes (one or more) + newline into a space.
      .replace(/\\+\n/g, " ")
      .replace(/\s*\n+/g, " ")
      .trim();

    entries.push({ title, org, orgUrl, dates, description });
  }

  return entries;
}
